/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tp_9;

class AppTest {
    void appHasAGreeting() {
        App classUnderTest = new App();
        System.out.println(classUnderTest.getClass() + "app should have a greeting");
    }
}
